services:
  - type: web
    name: prepforge-server
    env: node
    plan: free

    buildCommand: npm run install-all && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      - key: REDIS_URL
        sync: false

      - key: MONGODB_URI
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: CLIENT_URL
        sync: false